### ISSUE TITLE
Add option to move up or down a set number of migrations

### ISSUE THREAD

**Issue by carlbennettnz** [sheerun/knex-migrate#11]
When testing and debugging migrations, I often want to apply migrations one-at-a-time, checking the changes made by each one. Currently, this requires finding and typing out the timestamp for each migration.

An option like this would simplify this workflow:

```
$ knex-migrate up --number 1
$ knex-migrate down -n 1
```

Alternatively, to support just the more common use case of a single migration at a time:

```
$ knex-migrate up --one
$ knex-migrate down -1
```

Happy to send in a PR if you think this would be useful.

**Comment by kylealwyn** [comment]
suggesting `--count`

**Comment by carlbennettnz** [comment]
Agreed – that's clearer

**Comment by sheerun** [comment]
Yes please :) I think the implementation can be difficult, because it'll require much tighter cooperation with umzug (and probably imlementing this feature there first).

I think we don't need to introduce another flag, but just extend the meaning of `--from` and `--to` flags.

1. If passed number is less than 1000, assume it's the number of steps
2. Else, assume it's the number of migration

e.g:

- `knex-migrate up 20170629` - migrates up to migration 20170629
- `knex-migrate down 0` - migrates down to migration 0 (current behavior)
- `knex-migrate down 1` - migrates down to migration 1 (new behavior)
- `knex-migrate down -3` - migrates down to 3rd migraton from the end (new behavior)
- `knex-migrate up -1` - migrates up to next to last migration (new behavior)

**Comment by sheerun** [comment]
OK, we could also have migration in steps, but I'd name the flag `--step`, not `--count` or `--number` because these are not clear. e.g:

- `knex-migrate up 20170629 --step` - migrates up to migration 20170629, just one step
- `knex-migrate down 20170101 --step` - migrates down to migration 20170101, just one step
- `knex-migrate down 0 --step 2` - migrates down all migrations (but just two steps)
- `knex-migrate up --step` - migrates up just one step
- `knex-migrate up --step 2` - migrates up just two steps

**Comment by carlbennettnz** [comment]
Keeping the number of steps as a separate option is cleaner, IMO. I like `--step` though.

Just checking, you're saying `up 20171218 --step` should make a single step towards that version, or nothing if we're already there, right?

I've had a look at how it could be implemented. I think we can avoid changes to umzug by just calling `umzug.history()`/`.pending()` and using that to set `from` and `to` properly. Something along the lines of:

```js
const pending = await umzug.pending()
const to = pending[Math.min(steps, pending.length) - 1]

if (to) {
  umzugOpts.to = to.file
}
```

**Comment by sheerun** [comment]
> Just checking, you're saying up 20171218 --step should make a single step towards that version, or nothing if we're already there, right?

Yes, indeed

> I've had a look at how it could be implemented. I think we can avoid changes to umzug by just calling umzug.history()/.pending() and using that to set from and to properly.

Sounds good as long as it'll work for down migrations as well :)

**Comment by sheerun** [comment]
Implemented and released
